# Generated by Django 4.1.2 on 2022-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Follow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='post',
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block'), ('hide', 'hide'), ('ignore', 'ignore')], default='active', max_length=50),
        ),
    ]
