# Generated by Django 4.1.2 on 2022-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Follow', '0002_remove_friend_post_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='category',
            field=models.CharField(choices=[('Following', 'Following'), ('Followers', 'Followers'), ('Following', 'Following'), ('Mutual', 'Mutual'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
