# Generated by Django 4.1.2 on 2022-11-22 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Follow', '0003_alter_friend_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='category',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
        migrations.AddField(
            model_name='friend',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='mutual',
            field=models.ManyToManyField(related_name='mutual', to=settings.AUTH_USER_MODEL),
        ),
    ]
