# Generated by Django 4.1.2 on 2022-11-24 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Follow', '0005_alter_friend_followers_alter_friend_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='mutual',
            field=models.ManyToManyField(blank=True, related_name='mutual', to=settings.AUTH_USER_MODEL),
        ),
    ]
