# Generated by Django 4.1.2 on 2022-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
