# Generated by Django 4.1.2 on 2022-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
