# Generated by Django 4.1.2 on 2022-11-17 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0005_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
